Added tests for movement module and a bug
ctlai95/python-tetris pull request #35
Opened 2018-05-07 04:40 UTC by ctlai95

2018-05-27 04:31 UTC, henrytran28 requested changes

2018-05-27 05:34 UTC, ctlai95 commented
For the I-spins I followed this instead: http://tetris.wikia.com/wiki/I-spins_in_SRS
which all passed so i think we're good :)

2018-05-27 05:36 UTC, ctlai95 commented
tests failed gg

2018-06-04 03:35 UTC, henrytran28 requested changes

2018-06-04 03:35 UTC, henrytran28 commented on src/movement/movement_test.py
> +                movement.board.current_tetromino.origin.y) == (twist_test.initial_position.x, twist_test.initial_position.y)
Use the equals function

2018-06-04 03:35 UTC, henrytran28 commented on src/movement/movement_test.py
> +        for board_square_position in twist_test.boundary_positions:
boundary position

2018-06-04 03:35 UTC, henrytran28 commented on src/movement/movement_test.py
> +                print(movement.board.get_combined_matrix_string())
delet this nephew

2018-10-09 03:57 UTC, closed without merging